"%prod":
  quarkus:
    datasource:
      reactive:
        postgresql:
          ssl-mode: verify-ca
quarkus:
  http:
    port: ${PORT:8080}
  datasource:
    reactive:
      trust-all: true
      trust-certificate-pem: true
      url: ${DATABASE_URL:postgres://localhost:5432/registrar}
    username: ${DATABASE_USERNAME:registrar}
    password: ${DATABASE_PASSWORD:registrar}
  log:
    level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %X %s%e%n"
    category:
      "ru.craftysoft":
        min-level: TRACE
        level: TRACE