quarkus:
  http:
    port: ${PORT:8080}
  datasource:
    reactive:
      trust-all: true
      trust-certificate-pem: true
      url: ${DATABASE_URL:postgres://localhost:5432/registrar}
      postgresql:
        ssl-mode: verify-ca
    username: ${DATABASE_USERNAME:registrar}
    password: ${DATABASE_PASSWORD:registrar}
  log:
    level: INFO
    category:
      "ru.craftysoft":
        min-level: TRACE
        level: TRACE