CREATE SCHEMA registrar;

CREATE USER registrar WITH
    LOGIN
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    INHERIT
    NOREPLICATION
    CONNECTION LIMIT -1
    PASSWORD 'registrar';

GRANT CONNECT ON DATABASE registrar TO registrar;